version: "3"
services:
  flask:
    container_name: flask
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ..:/src
    environment:
      - FLASK_APP=main_app.py
    command: flask run --host 0.0.0.0 --port 5000
